create database project;
use project;
select * from dim_date;
desc dim_date;
alter table dim_date modify column date Date;
select * from dim_hotels;
desc dim_hotels;
select * from dim_rooms;
select * from agg_bookings;
desc agg_bookings;
alter table agg_bookings modify column check_in_date date;
alter table agg_bookings change column room_category room_id text;
select * from fact_bookings;
desc fact_bookings;
alter table fact_bookings modify column check_in_date date;
alter table fact_bookings change column room_category room_id text;
alter table fact_bookings modify column booking_date date;
alter table fact_bookings modify column checkout_date date;
alter table fact_bookings modify column customer_id text;

select fb.booking_id, 
	fb.property_id,
    dh.property_name, 
    dh.category as hotel_category, 
    dh.city, 
    fb.check_in_date,
    dd.`mmm yy` as check_in_month,
	dd.`week no` as check_in_week, 
    dd.day_type as check_in_day_type, 
	fb.checkout_date, 
    fb.no_guests,
    fb.room_id,
    dr.room_class, 
    fb.booking_platform,
	fb.ratings_given, 
    fb.booking_status, 
    fb.revenue_generated, 
    fb.revenue_realized,
    fab.successful_bookings, 
    fab.capacity from fact_bookings as fb
left join dim_hotels as dh on fb.property_id = dh.property_id left join dim_date as dd on fb.check_in_date = dd.date left join dim_rooms as dr
on fb.room_id = dr.room_id left join agg_bookings as fab on fb.property_id = fab.property_id and fb.check_in_date = fab.check_in_date and
fb.room_id = fab.room_id;

select country, sum(revenue_generated), sum(revenue_realized) from fact_bookings group by 1 order by 2 desc, 3 desc;

##--------------------------------city wise Total-------------------------------##
select a.city, sum(b.revenue_generated) as Total_generated, sum(b.revenue_realized) as Total_realized from dim_hotels as a right join fact_bookings as b on a.property_id = b.property_id
group by 1 order by  3 desc;

##-----------------------platform wise Total revenue---------------------------##
select booking_platform, sum(revenue_generated) as 'generated' , sum(revenue_realized) as realized
 from fact_bookings group by 1 order by 3 desc;

##----------------------total booking----------------------------##
select *, sum(status_count) over() as Total from(
select booking_status, count(booking_status) status_count
 from fact_bookings group by 1)abc;

##----------------cancel rate v/s successful rate v/s no show ------------------##
select round(count(if(booking_status = 'cancelled',1,null))/count(booking_status)*100,2) as cancel_rate, 
round(count(if(booking_status = 'checked out',1,null))/count(booking_status)*100,2) as checked_out_rate,
round(count(if(booking_status = 'no show',1,null))/count(booking_status)*100,2) as no_show_rate from fact_bookings;

##------------------------------property wise generated v/s realized--------------------------##
select a.property_name,sum(b.revenue_generated) as generated_revenue , sum(b.revenue_realized) as realized from dim_hotels as a join fact_bookings as b on
a.property_id = b.property_id group by 1 order by 3 desc;

##---------------------------- total revenue on days-----------------------------##
select a.day_type, sum(b.revenue_realized) as revenue_realized from fact_bookings as b join dim_date as a 
on a.date = b.check_in_date group by 1;

##----------------------------location wise count of bookings-------------------------##
select a.city, count(b.booking_id) as count_customers from dim_hotels as a join fact_bookings as b on a.property_id = b.property_id
group by 1 order by 2 desc;

##-------------------------------KPI-----------------------##
SELECT 
    concat(round(SUM(a.revenue_generated/1000000),2),'M') AS revenue_generated,
    concat(round(SUM(a.revenue_realized/1000000),2),'M')  AS total_revenue,
    COUNT(DISTINCT a.booking_id) AS total_bookings,
    COUNT(DISTINCT b.property_id) AS total_hotels,
    count(distinct a.booking_channel) as booking_channel
FROM fact_bookings AS a
JOIN dim_hotels AS b 
    ON a.property_id = b.property_id;

##------------------------------utilised capacity%------------------------------##
select 
	a.property_name, 
    concat(round(sum(b.successful_bookings)/sum(b.capacity)*100,2),'%') as Utilised_Capacity 
from agg_bookings as b 
join dim_hotels as a 
	on a.property_id = b.property_id group by 1 order by 2 desc;

##-----------------------monthly trend--------------------------------------##
select 
	monthname(a.date) as Month, 
    sum(b.revenue_realized) as Total_Revenue, 
    sum(b.revenue_generated) as Generated_revenue,
    count(b.booking_id) as Occupancy
from dim_date as a 
join fact_bookings as b 
on a.date=b.check_in_date group by 1 ;

##-----------------------revenue_generated by location & property-----------------------------##
select a.city, a.property_name, sum(b.revenue_generated) as total_revenue from dim_hotels as a join fact_bookings as b
on a.property_id=b.property_id group by 1,2 order by 3 desc;

##------------------------room class wise revenue---------------------------##
select a.room_class, sum(b.revenue_generated) as Total_revenue from dim_rooms as a join fact_bookings as b on a.room_id = b.room_id
group by 1 order by 2 desc;

##---------------------week wise Total revenue & bookings-------------------------------#
select a.`week no`, sum(b.revenue_generated) as Total_revenue, count(b.booking_id) as Total_bookings 
from dim_date as a left join fact_bookings as b on a.date = b.check_in_date
group by 1 order by 1;

##--------------------------Month Growth Rate-----------------------------------##
select *, ifnull(concat(round((Total_revenue-Previous_month)/previous_month*100,2),'%'),0) as Growth_rate 
from(
select
	monthname(a.date) as Month, sum(b.revenue_realized) as Total_revenue,
    ifnull(lag(sum(b.revenue_realized)) over(),0) as Previous_month
    from dim_date as a join fact_bookings as b on a.date = b.check_in_date 
    group by MONTHNAME(a.date), MONTH(a.date))abc;

##--------------------------week no Occupancy-------------------------------##
select a.`week no`, sum(b.successful_bookings) as Occupancy from dim_date as a  join 
agg_bookings as b on a.date = b.check_in_date
group by 1;

##-----------------------------week growth rate---------------------------##
select * , ifnull(concat(round((Total-Previous_week)/previous_week*100,2),'%'),0) as Growth_rate from(
select 
	a.`week no`,
    sum(b.revenue_realized) as Total, 
    ifnull(lag(sum(b.revenue_realized)) over(),0) as Previous_week
from dim_date as a  
join fact_bookings as b 
on a.date = b.check_in_date
group by 1)abc;






